### ISSUE TITLE
2023新版本 更新后  云编译固件   luci 菜单里不显示出来

### ISSUE THREAD

**Issue by wt971460266** [sirpdboy/luci-app-autotimeset#10]
更新后的插件 lede源码云编译  luci菜单不显示出来 请问啥时候可以修复
![image](https://user-images.githubusercontent.com/115206327/214070717-5456fc21-0038-4048-93af-e0192c26992a.png)

**Comment by MilesPoupart** [comment]
![image](https://user-images.githubusercontent.com/32707318/214216659-10d1b718-17f4-466a-aa65-a868ca9f048d.png)
同样的问题

**Comment by sirpdboy** [comment]
定时设置，是在管控菜单中，不在服务中。

**Comment by wt971460266** [comment]
lede 

> 定时设置，是在管控菜单中，不在服务中。
lede 固件 没有管控菜单

**Comment by touchsola** [comment]
> 

需要把
luci-app-autotimeset下面的
luasrc/controller/autotimeset.lua
这个文件第10行更改一下
原内容：
`page = entry({"admin","control","autotimeset"},cbi("autotimeset"),_("Scheduled Setting"),88)`
更改为：
`page = entry({"admin","system","autotimeset"},cbi("autotimeset"),_("Scheduled Setting"),88)`
重新编译后系统菜单里面就能显示出来了
