### ISSUE TITLE
OpenWRT最新版本安装时报错/etc/rc.common: /etc/init.d/autotimesetrun: line 8: syntax error: unexpected "}"

### ISSUE THREAD

**Issue by lushangkan** [sirpdboy/luci-app-autotimeset#19]
安装时报错
`/etc/rc.common: /etc/init.d/autotimesetrun: line 8: syntax error: unexpected "}"`
手动运行`/etc/init.d/autotimesetrun`同样报错
往`/etc/init.d/autotimesetrun`添加任意命令后报错消失

**Comment by sirpdboy** [comment]
好，问题收到，已经处理。

**Comment by kettly1260** [comment]
> 好，问题收到，已经处理。

请问是不是没更新编译啊，下载的还是有这个问题
