### ISSUE TITLE
配置保存后不生效

### ISSUE THREAD

**Issue by bleach1991** [sirpdboy/luci-app-autotimeset#2]
lean大的最新源码编译的x86_64，即使保存配置2遍后依旧不生效

**Comment by bleach1991** [comment]
版本应该是19.07的

**Comment by weweyes** [comment]
lienol_X64_19.07的不起作用，lean的最新源码xiaomi_ac2100也不起作用

**Comment by sirpdboy** [comment]
保存不起效 ，可能是init.d 中文件没执行权限。

**Comment by sirpdboy** [comment]
保留配置没有保存，一般是固件原因或者你固件没空间了。

**Comment by tianiue** [comment]
这个插件作者没有设置权限，编译前要自己把文件全部改成755才可以
