### ISSUE TITLE
lienol的源码，21.02分支编译后提示错误信息，无法显示界面

### ISSUE THREAD

**Issue by trombonist852** [sirpdboy/luci-app-autotimeset#4]
![微信图片_20210403161106](https://user-images.githubusercontent.com/13253090/113472657-3bd94780-9497-11eb-9511-9af70d2cdffe.png)
编译后进到插件界面提示：
/usr/lib/lua/luci/model/cbi/autotimeset.lua:2: module 'luci.model.ipkg' not found:
	no field package.preload['luci.model.ipkg']
	no file './luci/model/ipkg.lua'
	no file '/usr/share/lua/luci/model/ipkg.lua'
	no file '/usr/share/lua/luci/model/ipkg/init.lua'
	no file '/usr/lib/lua/luci/model/ipkg.lua'
	no file '/usr/lib/lua/luci/model/ipkg/init.lua'
	no file './luci/model/ipkg.so'
	no file '/usr/lib/lua/luci/model/ipkg.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/lib/lua/luci/model/cbi/autotimeset.lua:2: in function 'func'
	/usr/lib/lua/luci/cbi.lua:66: in function 'load'
	/usr/lib/lua/luci/dispatcher.lua:1353: in function '_cbi'
	/usr/lib/lua/luci/dispatcher.lua:1024: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:479: in function </usr/lib/lua/luci/dispatcher.lua:478>

望大神帮忙分析一下 感激不尽！

**Comment by trombonist852** [comment]
已找到解决方法 安装 luci-lib-ipkg后解决

**Comment by rootphantomer** [comment]
我这还是不行，安装完 luci-lib-ipkg，要卸载再安装吗？
